$schema: https://json-schema.org/draft/2020-12/schema
description: Sensor, Observation, Sample, and Actuator (SOSA)
anyOf:
- $schema: https://json-schema.org/draft/2020-12/schema
  description: Example SOSA Vector Observation
  allOf:
  - $ref: properties/observation/schema.yaml
  - type: object
    properties:
      hasResult:
        properties:
          pose:
            $ref: ../../geo/geopose/basic-ypr/schema.yaml
          distance:
            type: number
            x-jsonld-id: http://example.com/properties/distance
            x-jsonld-type: http://www.w3.org/2001/XMLSchema#float
    required:
    - hasResult
    not:
      required:
      - hasSimpleResult
  x-jsonld-extra-terms: {}
- $schema: https://json-schema.org/draft/2020-12/schema
  description: Example SOSA Vector Observation
  allOf:
  - $ref: features/observation/schema.yaml
  - type: object
    properties:
      properties:
        $ref: examples/vectorObservation/schema.yaml
  x-jsonld-extra-terms: {}
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA Observation Feature
  type: object
  allOf:
  - $ref: ../../geo/json-fg/feature/schema.yaml
  - type: object
    properties:
      properties:
        $ref: properties/observation/schema.yaml
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasResult: http://www.w3.org/ns/sosa/hasResult
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    resultTime: http://www.w3.org/ns/sosa/resultTime
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    forProperty: http://www.w3.org/ns/ssn/forProperty
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    Sample: http://www.w3.org/ns/sosa/Sample
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    usedProcedure: http://www.w3.org/ns/sosa/usedProcedure
    observes: http://www.w3.org/ns/sosa/observes
    hasSample: http://www.w3.org/ns/sosa/hasSample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
    madeBySensor: http://www.w3.org/ns/sosa/madeBySensor
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    observedProperty: http://www.w3.org/ns/sosa/observedProperty
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    hasInput: http://www.w3.org/ns/ssn/hasInput
    hasMember: http://www.w3.org/ns/sosa/hasMember
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    Observation: http://www.w3.org/ns/sosa/Observation
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    hasFeatureOfInterest: http://www.w3.org/ns/sosa/hasFeatureOfInterest
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    phenomenonTime: http://www.w3.org/ns/sosa/phenomenonTime
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    detects: http://www.w3.org/ns/ssn/detects
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    implements: http://www.w3.org/ns/ssn/implements
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA Observation Feature
  allOf:
  - $ref: ../../geo/json-fg/featureCollection/schema.yaml
  - type: object
    properties:
      properties:
        $ref: properties/observationCollection/schema.yaml
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasResult: http://www.w3.org/ns/sosa/hasResult
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    resultTime: http://www.w3.org/ns/sosa/resultTime
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    forProperty: http://www.w3.org/ns/ssn/forProperty
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    Sample: http://www.w3.org/ns/sosa/Sample
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    usedProcedure: http://www.w3.org/ns/sosa/usedProcedure
    observes: http://www.w3.org/ns/sosa/observes
    hasSample: http://www.w3.org/ns/sosa/hasSample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
    madeBySensor: http://www.w3.org/ns/sosa/madeBySensor
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    observedProperty: http://www.w3.org/ns/sosa/observedProperty
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    hasInput: http://www.w3.org/ns/ssn/hasInput
    hasMember: http://www.w3.org/ns/sosa/hasMember
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    Observation: http://www.w3.org/ns/sosa/Observation
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    hasFeatureOfInterest: http://www.w3.org/ns/sosa/hasFeatureOfInterest
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    phenomenonTime: http://www.w3.org/ns/sosa/phenomenonTime
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    detects: http://www.w3.org/ns/ssn/detects
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    implements: http://www.w3.org/ns/ssn/implements
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA Observation
  type: object
  properties:
    resultTime:
      type: string
      format: date-time
      x-jsonld-id: http://www.w3.org/ns/sosa/resultTime
    phenomenonTime:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/phenomenonTime
    hasFeatureOfInterest:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/hasFeatureOfInterest
      x-jsonld-type: '@id'
    observedProperty:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/observedProperty
    usedProcedure:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/usedProcedure
      x-jsonld-type: '@id'
    madeBySensor:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/madeBySensor
      x-jsonld-type: '@id'
    hasResult:
      x-jsonld-id: http://www.w3.org/ns/sosa/hasResult
    hasSimpleResult:
      x-jsonld-id: http://www.w3.org/ns/sosa/hasSimpleResult
  oneOf:
  - required:
    - hasResult
  - required:
    - hasSimpleResult
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasResult: http://www.w3.org/ns/sosa/hasResult
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    forProperty: http://www.w3.org/ns/ssn/forProperty
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    Sample: http://www.w3.org/ns/sosa/Sample
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    observes: http://www.w3.org/ns/sosa/observes
    hasSample: http://www.w3.org/ns/sosa/hasSample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    hasInput: http://www.w3.org/ns/ssn/hasInput
    hasMember: http://www.w3.org/ns/sosa/hasMember
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    Observation: http://www.w3.org/ns/sosa/Observation
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    detects: http://www.w3.org/ns/ssn/detects
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    implements: http://www.w3.org/ns/ssn/implements
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA ObservationCollection
  type: object
  properties:
    resultTime:
      type: string
      format: date-time
      x-jsonld-id: http://www.w3.org/ns/sosa/resultTime
    phenomenonTime:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/phenomenonTime
    hasFeatureOfInterest:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/hasFeatureOfInterest
      x-jsonld-type: '@id'
    observedProperty:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/observedProperty
    usedProcedure:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/usedProcedure
      x-jsonld-type: '@id'
    madeBySensor:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/madeBySensor
      x-jsonld-type: '@id'
    hasMember:
      type: array
      items:
        oneOf:
        - $ref: properties/observation/schema.yaml
        - type: string
      minItems: 1
      x-jsonld-id: http://www.w3.org/ns/sosa/hasMember
  required:
  - hasMember
  not:
    anyOf:
    - required:
      - hasResult
    - required:
      - hasSimpleResult
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasResult: http://www.w3.org/ns/sosa/hasResult
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    forProperty: http://www.w3.org/ns/ssn/forProperty
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    Sample: http://www.w3.org/ns/sosa/Sample
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    observes: http://www.w3.org/ns/sosa/observes
    hasSample: http://www.w3.org/ns/sosa/hasSample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    hasInput: http://www.w3.org/ns/ssn/hasInput
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    Observation: http://www.w3.org/ns/sosa/Observation
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    detects: http://www.w3.org/ns/ssn/detects
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    implements: http://www.w3.org/ns/ssn/implements
