$schema: https://json-schema.org/draft/2020-12/schema
description: Sensor, Observation, Sample, and Actuator (SOSA)
anyOf:
- $schema: https://json-schema.org/draft/2020-12/schema
  description: Example SOSA Vector Observation
  allOf:
  - $ref: properties/observation/schema.yaml
  - type: object
    properties:
      hasResult:
        properties:
          pose:
            $ref: ../../geo/geopose/basic-ypr/schema.yaml
          distance:
            type: number
            x-jsonld-id: http://example.com/properties/distance
            x-jsonld-type: http://www.w3.org/2001/XMLSchema#float
    required:
    - hasResult
    not:
      required:
      - hasSimpleResult
- $schema: https://json-schema.org/draft/2020-12/schema
  description: Example SOSA Vector Observation
  allOf:
  - $ref: features/observation/schema.yaml
  - type: object
    properties:
      properties:
        $ref: examples/vectorObservation/schema.yaml
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA Observation Feature
  type: object
  allOf:
  - $ref: ../../geo/json-fg/feature/schema.yaml
  - type: object
    properties:
      properties:
        $ref: properties/observation/schema.yaml
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    resultTime: http://www.w3.org/ns/sosa/resultTime
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    hasInput: http://www.w3.org/ns/ssn/hasInput
    madeBySensor: http://www.w3.org/ns/sosa/madeBySensor
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    features: http://www.w3.org/ns/sosa/hasMember
    phenomenonTime: http://www.w3.org/ns/sosa/phenomenonTime
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    observedProperty: http://www.w3.org/ns/sosa/observedProperty
    detects: http://www.w3.org/ns/ssn/detects
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    Sample: http://www.w3.org/ns/sosa/Sample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    Observation: http://www.w3.org/ns/sosa/Observation
    implements: http://www.w3.org/ns/ssn/implements
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    hasFeatureOfInterest: http://www.w3.org/ns/sosa/hasFeatureOfInterest
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasMember: http://www.w3.org/ns/sosa/hasMember
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    forProperty: http://www.w3.org/ns/ssn/forProperty
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    observes: http://www.w3.org/ns/sosa/observes
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    hasSample: http://www.w3.org/ns/sosa/hasSample
    hasResult: http://www.w3.org/ns/sosa/hasResult
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    usedProcedure: http://www.w3.org/ns/sosa/usedProcedure
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA Observation Feature
  allOf:
  - $ref: ../../geo/json-fg/featureCollection/schema.yaml
  - type: object
    properties:
      properties:
        $ref: properties/observationCollection/schema.yaml
      features:
        type: array
        items:
          oneOf:
          - $ref: features/observation/schema.yaml
          - type: string
        x-jsonld-id: http://www.w3.org/ns/sosa/hasMember
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    resultTime: http://www.w3.org/ns/sosa/resultTime
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    hasInput: http://www.w3.org/ns/ssn/hasInput
    madeBySensor: http://www.w3.org/ns/sosa/madeBySensor
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    phenomenonTime: http://www.w3.org/ns/sosa/phenomenonTime
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    observedProperty: http://www.w3.org/ns/sosa/observedProperty
    detects: http://www.w3.org/ns/ssn/detects
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    Sample: http://www.w3.org/ns/sosa/Sample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    Observation: http://www.w3.org/ns/sosa/Observation
    implements: http://www.w3.org/ns/ssn/implements
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    hasFeatureOfInterest: http://www.w3.org/ns/sosa/hasFeatureOfInterest
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasMember: http://www.w3.org/ns/sosa/hasMember
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    forProperty: http://www.w3.org/ns/ssn/forProperty
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    observes: http://www.w3.org/ns/sosa/observes
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    hasSample: http://www.w3.org/ns/sosa/hasSample
    hasResult: http://www.w3.org/ns/sosa/hasResult
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    usedProcedure: http://www.w3.org/ns/sosa/usedProcedure
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA Observation
  type: object
  properties:
    resultTime:
      type: string
      format: date-time
      x-jsonld-id: http://www.w3.org/ns/sosa/resultTime
    phenomenonTime:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/phenomenonTime
    hasFeatureOfInterest:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/hasFeatureOfInterest
      x-jsonld-type: '@id'
    observedProperty:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/observedProperty
    usedProcedure:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/usedProcedure
      x-jsonld-type: '@id'
    madeBySensor:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/madeBySensor
      x-jsonld-type: '@id'
    hasResult:
      x-jsonld-id: http://www.w3.org/ns/sosa/hasResult
    hasSimpleResult:
      x-jsonld-id: http://www.w3.org/ns/sosa/hasSimpleResult
  oneOf:
  - required:
    - hasResult
  - required:
    - hasSimpleResult
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    hasInput: http://www.w3.org/ns/ssn/hasInput
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    features: http://www.w3.org/ns/sosa/hasMember
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    detects: http://www.w3.org/ns/ssn/detects
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    Sample: http://www.w3.org/ns/sosa/Sample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    Observation: http://www.w3.org/ns/sosa/Observation
    implements: http://www.w3.org/ns/ssn/implements
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasMember: http://www.w3.org/ns/sosa/hasMember
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    forProperty: http://www.w3.org/ns/ssn/forProperty
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    observes: http://www.w3.org/ns/sosa/observes
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    hasSample: http://www.w3.org/ns/sosa/hasSample
    hasResult: http://www.w3.org/ns/sosa/hasResult
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
- $schema: https://json-schema.org/draft/2020-12/schema
  description: SOSA ObservationCollection
  type: object
  properties:
    resultTime:
      type: string
      format: date-time
      x-jsonld-id: http://www.w3.org/ns/sosa/resultTime
    phenomenonTime:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/phenomenonTime
    hasFeatureOfInterest:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/hasFeatureOfInterest
      x-jsonld-type: '@id'
    observedProperty:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/observedProperty
    usedProcedure:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/usedProcedure
      x-jsonld-type: '@id'
    madeBySensor:
      type:
      - object
      - string
      x-jsonld-id: http://www.w3.org/ns/sosa/madeBySensor
      x-jsonld-type: '@id'
  not:
    anyOf:
    - required:
      - hasResult
    - required:
      - hasSimpleResult
  x-jsonld-prefixes:
    sosa: http://www.w3.org/ns/sosa/
    ssn: http://www.w3.org/ns/ssn/
    ssn-system: http://www.w3.org/ns/ssn/systems/
  x-jsonld-extra-terms:
    deployedOnPlatform: http://www.w3.org/ns/ssn/deployedOnPlatform
    isHostedBy: http://www.w3.org/ns/sosa/isHostedBy
    inDeployment: http://www.w3.org/ns/ssn/inDeployment
    hasInput: http://www.w3.org/ns/ssn/hasInput
    implementedBy: http://www.w3.org/ns/ssn/implementedBy
    hosts: http://www.w3.org/ns/sosa/hosts
    hasOperatingProperty: http://www.w3.org/ns/ssn/systems/hasOperatingProperty
    features: http://www.w3.org/ns/sosa/hasMember
    hasSurvivalProperty: http://www.w3.org/ns/ssn/systems/hasSurvivalProperty
    detects: http://www.w3.org/ns/ssn/detects
    madeByActuator: http://www.w3.org/ns/sosa/madeByActuator
    hasSimpleResult: http://www.w3.org/ns/sosa/hasSimpleResult
    hasOperatingRange: http://www.w3.org/ns/ssn/systems/hasOperatingRange
    Sample: http://www.w3.org/ns/sosa/Sample
    wasOriginatedBy: http://www.w3.org/ns/ssn/wasOriginatedBy
    hasSystemCapability: http://www.w3.org/ns/ssn/systems/hasSystemCapability
    Observation: http://www.w3.org/ns/sosa/Observation
    implements: http://www.w3.org/ns/ssn/implements
    madeActuation: http://www.w3.org/ns/sosa/madeActuation
    hasOutput: http://www.w3.org/ns/ssn/hasOutput
    actsOnProperty: http://www.w3.org/ns/sosa/actsOnProperty
    isObservedBy: http://www.w3.org/ns/sosa/isObservedBy
    isSampleOf: http://www.w3.org/ns/sosa/isSampleOf
    hasSystemProperty: http://www.w3.org/ns/ssn/systems/hasSystemProperty
    hasMember: http://www.w3.org/ns/sosa/hasMember
    isActedOnBy: http://www.w3.org/ns/sosa/isActedOnBy
    isFeatureOfInterestOf: http://www.w3.org/ns/sosa/isFeatureOfInterestOf
    forProperty: http://www.w3.org/ns/ssn/forProperty
    hasSurvivalRange: http://www.w3.org/ns/ssn/systems/hasSurvivalRange
    observes: http://www.w3.org/ns/sosa/observes
    isProxyFor: http://www.w3.org/ns/ssn/isProxyFor
    hasDeployment: http://www.w3.org/ns/ssn/hasDeployment
    qualityOfObservation: http://www.w3.org/ns/ssn/systems/qualityOfObservation
    isPropertyOf: http://www.w3.org/ns/ssn/isPropertyOf
    hasSample: http://www.w3.org/ns/sosa/hasSample
    hasResult: http://www.w3.org/ns/sosa/hasResult
    inCondition: http://www.w3.org/ns/ssn/systems/inCondition
    isResultOf: http://www.w3.org/ns/sosa/isResultOf
    madeSampling: http://www.w3.org/ns/sosa/madeSampling
    madeBySampler: http://www.w3.org/ns/sosa/madeBySampler
    hasSubSystem: http://www.w3.org/ns/ssn/hasSubSystem
    deployedSystem: http://www.w3.org/ns/ssn/deployedSystem
    madeObservation: http://www.w3.org/ns/sosa/madeObservation
    hasProperty: http://www.w3.org/ns/ssn/hasProperty
