name: OGC Main
abstract:
description: |
  
  The OGC Building Blocks register provides an overview of a series of building blocks managed by the OGC community, including published standards,  
  ![](https://lucid.app/publicSegments/view/9d075f82-8611-4f32-83eb-994143669cc8/image.png)
identifier-prefix: ogc.

imports: []

sparql:
  push: https://defs-dev.opengis.net/fuseki/data
  graph: https://blocks.ogc.org/
  query: https://defs-dev.opengis.net/fuseki/query