allOf:
  - $ref: https://geojson.org/schema/FeatureCollection.json
  - type: object
    properties:
      links:
        type: array
        items:
          $ref: bblocks://ogc.ogc-utils.json-link
      timeStamp:
        type: string
        format: date-time
      numberMatched:
        type: integer
        minimum: 0
      numberReturned:
        type: integer
        minimum: 0
      features:
        type: array
        items:
          $ref: bblocks://ogc.geo.features.feature
