type: object
required:
  - id
  - links
properties:
  id:
    type: string
  title:
    type: string
  description:
    type: string
  links:
    type: array
    items:
      $ref: bblocks://ogc.ogc-utils.json-link
  extent:
    $ref: json-extent.yaml
  itemType:
    type: string
    default: feature
  crs:
    type: array
    items:
      type: string
    default:
      - http://www.opengis.net/def/crs/OGC/1.3/CRS84
