$schema: https://json-schema.org/draft/2019-09/schema
$id: https://beta.schemas.opengis.net/json-fg/feature.json
title: a JSON-FG Feature
description: This JSON Schema is part of JSON-FG version 0.1.1
type: object
required:
- type
- time
- place
- geometry
- properties
properties:
  type:
    type: string
    enum:
    - Feature
    x-jsonld-id: '@type'
  id:
    oneOf:
    - type: number
    - type: string
    x-jsonld-id: '@id'
  featureType:
    $ref: featuretype.json
  links:
    type: array
    items:
      $ref: link.json
  time:
    $ref: time.json
  coordRefSys:
    $ref: coordrefsys.json
  place:
    $ref: place.json
  geometry:
    $ref: geometry.json
    x-jsonld-id: https://purl.org/geojson/vocab#geometry
  properties:
    oneOf:
    - type: 'null'
    - type: object
    x-jsonld-id: https://purl.org/geojson/vocab#properties
x-jsonld-extra-terms:
  Feature: https://purl.org/geojson/vocab#Feature
  FeatureCollection: https://purl.org/geojson/vocab#FeatureCollection
  GeometryCollection: https://purl.org/geojson/vocab#GeometryCollection
  LineString: https://purl.org/geojson/vocab#LineString
  MultiLineString: https://purl.org/geojson/vocab#MultiLineString
  MultiPoint: https://purl.org/geojson/vocab#MultiPoint
  MultiPolygon: https://purl.org/geojson/vocab#MultiPolygon
  Point: https://purl.org/geojson/vocab#Point
  Polygon: https://purl.org/geojson/vocab#Polygon
  bbox:
    x-jsonld-container: '@list'
    x-jsonld-id: https://purl.org/geojson/vocab#bbox
  coordinates:
    x-jsonld-container: '@list'
    x-jsonld-id: https://purl.org/geojson/vocab#coordinates
  features:
    x-jsonld-container: '@set'
    x-jsonld-id: https://purl.org/geojson/vocab#features
x-jsonld-prefixes:
  geojson: https://purl.org/geojson/vocab#
