allOf:
  - $ref: bblocks://ogc.geo.common.data_types.geojson
  - type: object
    properties:
      links:
        type: array
        items:
          $ref: bblocks://ogc.ogc-utils.json-link
      type:
        const: Feature
    required:
      - type
      - geometry
      - properties
