description: 'Basic-YPR: Basic GeoPose using yaw, pitch, and roll to specify orientation'
definitions:
  angles:
    type: object
    properties:
      yaw:
        type: number
        x-jsonld-id: http://example.com/geopose/yaw
      pitch:
        type: number
        x-jsonld-id: http://example.com/geopose/pitch
      roll:
        type: number
        x-jsonld-id: http://example.com/geopose/roll
    required:
    - yaw
    - pitch
    - roll
    x-jsonld-extra-terms:
      position: http://example.com/geopose/position
      angles: http://example.com/geopose/angles
      lat: http://example.com/geopose/lat
      lon: http://example.com/geopose/lon
      h: http://example.com/geopose/h
      longitude: http://www.w3.org/2003/01/geo/wgs84_pos#long
      latitude: http://www.w3.org/2003/01/geo/wgs84_pos#lat
      height: http://example.com/geopose/height
      rotations: http://example.com/geopose/rotations
  Position:
    type: object
    properties:
      lat:
        type: number
        x-jsonld-id: http://example.com/geopose/lat
      lon:
        type: number
        x-jsonld-id: http://example.com/geopose/lon
      h:
        type: number
        x-jsonld-id: http://example.com/geopose/h
    required:
    - lat
    - lon
    - h
    x-jsonld-extra-terms:
      position: http://example.com/geopose/position
      angles: http://example.com/geopose/angles
      yaw: http://example.com/geopose/yaw
      pitch: http://example.com/geopose/pitch
      roll: http://example.com/geopose/roll
      longitude: http://www.w3.org/2003/01/geo/wgs84_pos#long
      latitude: http://www.w3.org/2003/01/geo/wgs84_pos#lat
      height: http://example.com/geopose/height
      rotations: http://example.com/geopose/rotations
type: object
properties:
  position:
    $ref: '#/definitions/Position'
    x-jsonld-id: http://example.com/geopose/position
  angles:
    $ref: '#/definitions/angles'
    x-jsonld-id: http://example.com/geopose/angles
required:
- position
- angles
x-jsonld-extra-terms:
  longitude: http://www.w3.org/2003/01/geo/wgs84_pos#long
  latitude: http://www.w3.org/2003/01/geo/wgs84_pos#lat
  height: http://example.com/geopose/height
  rotations: http://example.com/geopose/rotations
x-jsonld-prefixes:
  geopose: http://example.com/geopose/
  geo: http://www.w3.org/2003/01/geo/wgs84_pos#
$id: https://schemas.opengis.net/geopose/1.0/schemata/GeoPose.Basic.YPR.Schema.json
