allOf:
  - $ref: bblocks://ogc.geo.features.feature

  # Copied from https://beta.schemas.opengis.net/json-fg/feature.json, with time and place removed from required
  - type: object
    required:
      - type
      - geometry
      - properties
    properties:
      type:
        type: string
        enum:
          - Feature
      id:
        oneOf:
          - type: number
          - type: string
      featureType:
        $ref: https://beta.schemas.opengis.net/json-fg/featuretype.json
      links:
        type: array
        items:
          allOf:
            - $ref: https://beta.schemas.opengis.net/json-fg/link.json
            - $ref: bblocks://ogc.ogc-utils.json-link
      time:
        $ref: https://beta.schemas.opengis.net/json-fg/time.json
      coordRefSys:
        $ref: https://beta.schemas.opengis.net/json-fg/coordrefsys.json
      place:
        $ref: https://beta.schemas.opengis.net/json-fg/place.json
      geometry:
        $ref: https://beta.schemas.opengis.net/json-fg/geometry.json
      properties:
        oneOf:
          - type: 'null'
          - type: object
