type: object
required:
  - links
  - collections
properties:
  links:
    type: array
    items:
      $ref: bblocks://ogc.ogc-utils.json-link
  collections:
    type: array
    items:
      $ref: bblocks://ogc.geo.common.data_types.ogc_collection
