name: Deploy static content to Pages

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
          submodules: recursive
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: '.'
      - name: Deploy to GH Pages
        id: deployment
        uses: actions/deploy-pages@v2
