name: Process Building Blocks

on:
  push:
    branches: [master]
  workflow_dispatch:
  schedule:
    - cron: 0 4 * * 0

jobs:
  validate-and-process:
    uses: opengeospatial/bblocks-postprocess/.github/workflows/validate-and-process.yml@master
    env:
      SPARQL_USERNAME: ${{ secrets.UPLOAD_GRAPH_STORE_USERNAME }}
      SPARQL_PASSWORD: ${{ secrets.UPLOAD_GRAPH_STORE_PASSWORD }}
    with:
      items_dir: registereditems
      register_file: register.json
      generated_docs_path: generateddocs
      annotated_path: annotated-schemas
      fail_on_error: 'false'
      clean: 'true'
      test_outputs_path: tests
      viewer_path: ./register/
